# Generated by Django 2.1.5 on 2019-06-03 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('location_x', models.FloatField(blank=True, default=None, null=True)),
                ('location_y', models.FloatField(blank=True, default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('rating', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('location_x', models.FloatField(blank=True, null=True)),
                ('location_y', models.FloatField(blank=True, null=True)),
                ('like', models.IntegerField(default=0)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_num', models.CharField(choices=[('1', '1호선'), ('2', '2호선'), ('3', '3호선'), ('4', '4호선'), ('5', '5호선'), ('6', '6호선'), ('7', '7호선'), ('8', '8호선'), ('9', '9호선'), ('A', '공항철도'), ('B', '분당선'), ('E', '전대에버라인'), ('G', '경춘선'), ('I', '인천1호선'), ('I2', '인천2호선'), ('K', '경의중앙선'), ('KK', '경강선'), ('S', '신분당선'), ('SU', '수인선'), ('T', '테스트'), ('U', '의정부경전철'), ('UI', '우이신설선')], max_length=3)),
                ('station_cd', models.CharField(max_length=4)),
                ('station_nm', models.CharField(max_length=20)),
                ('fr_code', models.CharField(max_length=5)),
                ('transfer_count', models.IntegerField(default=1)),
                ('naver_cd', models.CharField(blank=True, default='', max_length=10)),
                ('head_time', models.FloatField(null=True)),
                ('tail_time', models.FloatField(null=True)),
                ('tag_count', models.IntegerField(default=0)),
                ('head_station', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='head_station_set', to='dateapp.Station')),
                ('tail_station', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tail_station_set', to='dateapp.Station')),
            ],
            options={
                'ordering': ['fr_code'],
            },
        ),
        migrations.AddField(
            model_name='spot',
            name='near_stations',
            field=models.ManyToManyField(to='dateapp.Station'),
        ),
        migrations.AddField(
            model_name='review',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dateapp.Spot'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
