# Generated by Django 2.1.5 on 2019-06-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='head_station',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='station',
            name='tail_station',
            field=models.CharField(max_length=4),
        ),
    ]
