# Generated by Django 2.1.5 on 2019-06-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dateapp', '0002_auto_20190604_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='near_stations',
        ),
        migrations.AddField(
            model_name='spot',
            name='near_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dateapp.Station'),
        ),
    ]
