# Generated by Django 2.2.1 on 2019-06-11 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dateapp', '0005_auto_20190611_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='like',
            new_name='likes',
        ),
    ]
