# Generated by Django 2.2.1 on 2019-06-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dateapp', '0006_auto_20190611_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='likes',
            new_name='like',
        ),
    ]
