# Generated by Django 2.2.1 on 2019-06-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateapp', '0007_auto_20190611_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='like',
        ),
        migrations.AddField(
            model_name='spot',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
