# Generated by Django 2.2.1 on 2019-06-11 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dateapp', '0008_auto_20190611_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='name_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='spot',
            name='like',
        ),
        migrations.AddField(
            model_name='spot',
            name='like',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
