# Generated by Django 2.2.1 on 2019-06-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dateapp', '0009_auto_20190611_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='name_id',
        ),
    ]
